### ISSUE TITLE
Error after updating distro, inicial issue "from manga_ocr import MangaOcr ModuleNotFoundError: No module named 'manga_ocr'" Resolved, new issue does not have any indications of what is happening (more info in comments)

### ISSUE THREAD

**Issue by matthew-faber** [Ajatt-Tools/transformers_ocr#6]
```
$ transformers_ocr recognize [or transformers_ocr start, yields identical result]
/usr/bin/transformers_ocr: line 64: kill: (29717) - No such process
Started manga_ocr listener.
[katsumi@localhost ~]$ Traceback (most recent call last):
  File "/usr/lib/transformers_ocr/listener.py", line 8, in <module>
    from manga_ocr import MangaOcr
ModuleNotFoundError: No module named 'manga_ocr'
```

Attempted `transformers_ocr download `and got this error in the bottom.
![Screenshot from 2024-01-03 09-48-26](https://github.com/Ajatt-Tools/transformers_ocr/assets/29362787/7cfcf357-ab32-411c-8593-aaabb4e85934)

My attempts were: 

- Downloading multiple versions of torch (there is no torch version 1.0 but, 1.11 and beyond)
- Switching to xOrg from Wayland
There's isn't much I can think of to solve this as a layman towards these things.

**Comment by tatsumoto-ren** [comment]
`transformers_ocr purge`
then
`transformers_ocr download`

**Comment by matthew-faber** [comment]
@tatsumoto-ren 	~~copied it to the terminal, but the command does not exist~~

```
[katsumi@localhost ~]$ transformers_ocr purge
Unknown command.
Usage: transformers_ocr [COMMAND]

An OCR script that uses maim and manga-ocr.

Options:
recognize  OCR a part of the screen.
download   Download manga-ocr files.
start      Start listening.
stop       Stop listening.
help       Show this help screen.
[katsumi@localhost ~]$ 
```
~~Did `transformers_ocr start` just in case but to no avail~~
```
[katsumi@localhost ~]$ transformers_ocr start
/usr/bin/transformers_ocr: line 64: kill: (14294) - No such process
Started manga_ocr listener.
[katsumi@localhost ~]$ Traceback (most recent call last):
  File "/usr/lib/transformers_ocr/listener.py", line 8, in <module>
    from manga_ocr import MangaOcr
ModuleNotFoundError: No module named 'manga_ocr'

[katsumi@localhost ~]$ transformers_ocr purge
Unknown command.
Usage: transformers_ocr [COMMAND]

An OCR script that uses maim and manga-ocr.

Options:
recognize  OCR a part of the screen.
download   Download manga-ocr files.
start      Start listening.
stop       Stop listening.
help       Show this help screen.
[katsumi@localhost ~]$ 

```
~~Also used `transformers_ocr stop` before your suggested command yielding an identical output~~

**Comment by matthew-faber** [comment]
The error I opened an issue with is now gone after I have replaced the previous transformers_ocr file in my home directory and installed again with makefile. Now having access to the `purge` command, I initiated and afterwards initiated the `download` command. Though, a new issue appears; 
```
[katsumi@localhost ~]$ transformers_ocr recognize 
Started manga_ocr listener.

```
After I have initiated with the command `transformers_ocr recognize` , it maintains this in the terminal, and after I have taken a screenshot, nothing happens, nothing is saved in my clipboard.  If there's anything you want me to do, to better understand this issue, please do tell.

**Comment by matthew-faber** [comment]
Attempted restarting my pc as the layman's last resort to no avail

**Comment by tatsumoto-ren** [comment]
Are you using gnome?

**Comment by matthew-faber** [comment]
Yes. I'm sorry to be wasting your time on something that likely is a rare issue or just simple mistake in my part

**Comment by tatsumoto-ren** [comment]
Yes, I don't understand what can possibly go wrong here.
